### PR TITLE
Fix | "Update link in "Waiting for Confirmation" modal" |

### PR DESCRIPTION
**Pull request by eben619**
# Description

Updated the link from https://gooddollar.notion.site/How-do-transactions-work-in-web3-ccf11b4e16874a1682722a20c4e24742 to  https://docs.gooddollar.org/frequently-asked-questions/using-gooddollar#how-do-transactions-work-in-web3

About #211 

# How Has This Been Tested?

# Checklist:
- [x] PR title matches follow: (Feature|Bug|Chore) Task Name
- [x] My code follows the style guidelines of this project
- [x] I have followed all the instructions described in the initial task (check Definitions of Done)
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [x] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

### CODE REVIEW

**Comment by sirpy** [comment]
@eben619 why does it says the head ref contains hidden characters?
image

**Comment by eben619** [comment]
@sirpy I think I know why. Let me rectify it.

**Comment by eben619** [comment]
This was the original head with special characters. 




But it got hidden and formatted to this.

**Comment by decentralauren** [comment]
@sirpy  @L03TJ3 - this was closed but not actually finished - what happened?

**Comment by sirpy** [comment]
@decentralauren it was done elswhere

**Pull request closed without merging**
