### PR TITLE
workspaces hoisting limits

### PR DESCRIPTION
**Pull request by L03TJ3**
# Description
This changes the hoisting limits of the repository to be per package 

#108

### CODE REVIEW

**Comment by sirpy** [comment]
I still don't understand why do we need it

**Comment by L03TJ3** [comment]
@sirpy  Your own comment was on the issue discussed: 'sync versions or apply no-hoisting'.

Syncing versions caused the issue (specifically sdk-v2 bump on good-design), and isolated no-hoisting for a single package doesn't exists (anymore). setting the hoisting-limit to workspaces seems the only way.

The new @gooddollar/goodprotocol package is based on last yarn.lock still in the local node_modules of good-design package.
once you bump sdk-v2 to latest on good-design, it hoists the protocol package to the root of the mono-repo.
This breaks the build for both sdk-v2 and good-design

**Comment by sirpy** [comment]
at the same conversation i wrote that I synced it already and good-design builds just fine

**Comment by L03TJ3** [comment]
@sirpy you haven't. you only synced protocol package + added an ethers dep
sdk-v2 is at 0.120 not 0.121

**Review by johnsmith-gooddollar — CHANGES_REQUESTED** [review]
could we distinct code/lint changes from the deps fixes (and changes caused by them like imports updates) ? 
- the lint fixes you could commit directly without PR
- keep here just deps fixes & non-lint changes

**Comment by L03TJ3** [comment]
> could we distinct code/lint changes from the deps fixes (and changes caused by them like imports updates) ?
> 
> * the lint fixes you could commit directly without PR
> * keep here just deps fixes & non-lint changes

@johnsmith-gooddollar no we cannot. lint-staged would prevent us to commit

**Pull request merged**
