### PR TITLE
Claimflow: pool names

### PR DESCRIPTION
**Pull request by L03TJ3**
# Description

Pool names can be read from the registry, and should be fetched as part of the pool-details.

- [ ] WIP: read contract name from registry

About # (link your issue here)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

# Checklist:
- [ ] PR title matches follow: (Feature|Bug|Chore) Task Name
- [ ] My code follows the style guidelines of this project
- [ ] I have followed all the instructions described in the initial task (check Definitions of Done)
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added reference to a related issue in the repository
- [ ] I have added a detailed description of the changes proposed in the pull request. I am as descriptive as possible, assisting reviewers as much as possible.
- [ ] I have added screenshots related to my pull request (for frontend tasks)
- [ ] I have pasted a gif showing the feature.
- [ ] @mentions of the person or team responsible for reviewing proposed changes

### CODE REVIEW

**Comment by L03TJ3** [comment]
@sirpy I started on adding this but it is not finalized yet.

Todo's:
- [ ] destructure pool-name and remove hardcoded `RedTent`: https://github.com/GoodDollar/GoodWeb3-Mono/blob/7cbed7a3bcae9729a30ab5c5c6b65e923bb0be65/packages/sdk-v2/src/sdk/claim/utils/pools.ts#L70

Should be all, the rest is already handled

**Comment by sirpy** [comment]
@L03TJ3 what do you mean by pool name? the pool name isnt available from the blockchain. it can be read from the subgraph or ipfs.

**Comment by L03TJ3** [comment]
@sirpy I assumed projectId would be the pool-name? retrieved from `factory.registry`

**Comment by sirpy** [comment]
no thats the projectid, it can have multiple pools. each pool details is in the ipfs file but the subgraph parses it, so you can query the subgraph.
in our case we can make it hard coded for now

**Comment by L03TJ3** [comment]
we are not doing this right now so closing

**Pull request closed without merging**
