### PR TITLE
[GoodID] 122 Redtent Offer

### PR DESCRIPTION
**Pull request by sirpy**
# Description

Added basic wizard + sdks for uploading video and registering to redtent

### CODE REVIEW

**Comment by L03TJ3** [comment]
Design todo's will be moved to new PR. the functionality of the wizard has been tested / review and will be merged into ```116-credential-storage``` branche

**Comment by sirpy** [comment]
@L03TJ3 also add a ticket for the design.

**Comment by L03TJ3** [comment]
@sirpy https://github.com/GoodDollar/GoodWeb3-Mono/issues/122

**Comment by L03TJ3** [comment]
@sirpy https://github.com/GoodDollar/GoodWeb3-Mono/issues/121
https://github.com/GoodDollar/GoodWeb3-Mono/issues/146

**Pull request merged**
